    language: python # => 1

    python: # => 2

      - "3.8.1"

    services: # => 3

      - mysql

    env: # => 4

      -DJANGO=3.1.2 DB=mysql

    before_install: # => 5
      - pip install Django
      - pip install PyMySQL
      - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

    install: # => 6

      - pip install -r requirements.txt

    before_script: # => 7

      - mysql -e 'create database test;' -u root
    script: # => 8

      - python manage.py makemigrations
      - python manage.py migrate
      - python manage.py test
