# Generated by Django 3.1.2 on 2020-10-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
